export const staticLayoutData = {
  name: "UIKit Figma logo",
  lastModified: "2024-03-16T14:05:35Z",
  thumbnailUrl:
    "https://s3-alpha.figma.com/thumbnails/314e4c14-b5a1-4774-8c2e-9e3a0566c840?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ4GOSFWCQ7LBML6Z%2F20240314%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240314T000000Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a486b6e3d446088286f35f37e2838bc2af2771ca6097f661e28eb47bcc0b7220",
  version: "5357508694",
  role: "owner",
  editorType: "figma",
  linkAccess: "edit",
  nodes: {
    "10:299": {
      document: {
        id: "10:299",
        name: "Layout Test",
        type: "FRAME",
        scrollBehavior: "SCROLLS",
        blendMode: "PASS_THROUGH",
        children: [
          {
            id: "10:329",
            name: "Rows",
            type: "FRAME",
            scrollBehavior: "SCROLLS",
            blendMode: "PASS_THROUGH",
            children: [
              {
                id: "10:311",
                name: "Row 1",
                type: "FRAME",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                children: [
                  {
                    id: "10:312",
                    name: "Item 01",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:313",
                        name: "FILL",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 290,
                          y: -852.5,
                          width: 37,
                          height: 22,
                        },
                        absoluteRenderBounds: {
                          x: 291.1796875,
                          y: -847.7890625,
                          width: 35.375,
                          height: 13.1171875,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "FILL",
                        style: {
                          fontFamily: "Comic Sans MS",
                          fontPostScriptName: "ComicSansMS-Bold",
                          fontWeight: 700,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 22.296875,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 254,
                      y: -856.5,
                      width: 109,
                      height: 30,
                    },
                    absoluteRenderBounds: {
                      x: 254,
                      y: -856.5,
                      width: 109,
                      height: 30,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 1,
                    layoutSizingHorizontal: "FILL",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "10:314",
                    name: "Item 02",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:315",
                        name: "2",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 436.5,
                          y: -852.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 437.5078125,
                          y: -848.96875,
                          width: 8.03125,
                          height: 11.46875,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "2",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 387,
                      y: -856.5,
                      width: 109,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 387,
                      y: -856.5,
                      width: 109,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 1,
                    layoutSizingHorizontal: "FILL",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "10:316",
                    name: "Item 03",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:317",
                        name: "3",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 569.5,
                          y: -852.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 570.2109375,
                          y: -848.96875,
                          width: 8.4609375,
                          height: 11.6640625,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "3",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 520,
                      y: -856.5,
                      width: 109,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 520,
                      y: -856.5,
                      width: 109,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 1,
                    layoutSizingHorizontal: "FILL",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                ],
                absoluteBoundingBox: {
                  x: 254,
                  y: -856.5,
                  width: 375,
                  height: 30,
                },
                absoluteRenderBounds: {
                  x: 254,
                  y: -856.5,
                  width: 375,
                  height: 30,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "STRETCH",
                layoutGrow: 0,
                layoutSizingHorizontal: "FILL",
                layoutSizingVertical: "HUG",
                clipsContent: false,
                background: [],
                fills: [],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "INSIDE",
                backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                layoutMode: "HORIZONTAL",
                itemSpacing: 24,
                primaryAxisSizingMode: "FIXED",
                layoutWrap: "NO_WRAP",
                effects: [],
              },
              {
                id: "36:340",
                name: "Row 3",
                type: "FRAME",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                children: [
                  {
                    id: "36:341",
                    name: "Item 01",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "36:342",
                        name: "FIXED",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 278,
                          y: -814.5,
                          width: 44,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 279.265625,
                          y: -810.7734375,
                          width: 41.8515625,
                          height: 11.2734375,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "FIXED",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 254,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 254,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "FIXED",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "36:343",
                    name: "Item 02",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "36:344",
                        name: "2",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 436.5,
                          y: -814.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 437.5078125,
                          y: -810.96875,
                          width: 8.03125,
                          height: 11.46875,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "2",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 395.5,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 395.5,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "FIXED",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "36:345",
                    name: "Item 03",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "36:346",
                        name: "3",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 578,
                          y: -814.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 578.7109375,
                          y: -810.96875,
                          width: 8.4609375,
                          height: 11.6640625,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "3",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 537,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 537,
                      y: -818.5,
                      width: 92,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "FIXED",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                ],
                absoluteBoundingBox: {
                  x: 254,
                  y: -818.5,
                  width: 375,
                  height: 27,
                },
                absoluteRenderBounds: {
                  x: 254,
                  y: -818.5,
                  width: 375,
                  height: 27,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "STRETCH",
                layoutGrow: 0,
                layoutSizingHorizontal: "FILL",
                layoutSizingVertical: "HUG",
                clipsContent: false,
                background: [],
                fills: [],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "INSIDE",
                backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                layoutMode: "HORIZONTAL",
                itemSpacing: 32,
                primaryAxisSizingMode: "FIXED",
                primaryAxisAlignItems: "SPACE_BETWEEN",
                layoutWrap: "NO_WRAP",
                effects: [],
              },
              {
                id: "10:310",
                name: "Row 2",
                type: "FRAME",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                children: [
                  {
                    id: "10:307",
                    name: "Second Item 01",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:304",
                        name: "HUG",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 271,
                          y: -779.5,
                          width: 35,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 272.3515625,
                          y: -775.96875,
                          width: 32.6328125,
                          height: 11.6640625,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "HUG",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 254,
                      y: -783.5,
                      width: 69,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 254,
                      y: -783.5,
                      width: 69,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "FIXED",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "10:308",
                    name: "Second Item 02",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:305",
                        name: "2",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 436,
                          y: -779.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 437.0078125,
                          y: -775.96875,
                          width: 8.03125,
                          height: 11.46875,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "2",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 405.5,
                      y: -783.5,
                      width: 71,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 405.5,
                      y: -783.5,
                      width: 71,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "FIXED",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    counterAxisSizingMode: "FIXED",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                  {
                    id: "10:309",
                    name: "Second Item 03",
                    type: "FRAME",
                    scrollBehavior: "SCROLLS",
                    blendMode: "PASS_THROUGH",
                    children: [
                      {
                        id: "10:306",
                        name: "3",
                        type: "TEXT",
                        scrollBehavior: "SCROLLS",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                          x: 589,
                          y: -779.5,
                          width: 10,
                          height: 19,
                        },
                        absoluteRenderBounds: {
                          x: 589.7109375,
                          y: -775.96875,
                          width: 8.4609375,
                          height: 11.6640625,
                        },
                        constraints: { vertical: "TOP", horizontal: "LEFT" },
                        layoutAlign: "INHERIT",
                        layoutGrow: 0,
                        layoutSizingHorizontal: "HUG",
                        layoutSizingVertical: "HUG",
                        fills: [
                          {
                            blendMode: "NORMAL",
                            type: "SOLID",
                            color: { r: 1, g: 1, b: 1, a: 1 },
                          },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "3",
                        style: {
                          fontFamily: "SF Pro Display",
                          fontPostScriptName: "SFProDisplay-Semibold",
                          fontWeight: 600,
                          textAutoResize: "WIDTH_AND_HEIGHT",
                          fontSize: 16,
                          textAlignHorizontal: "CENTER",
                          textAlignVertical: "TOP",
                          letterSpacing: 0,
                          lineHeightPx: 19.09375,
                          lineHeightPercent: 100,
                          lineHeightUnit: "INTRINSIC_%",
                        },
                        layoutVersion: 4,
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        lineTypes: ["NONE"],
                        lineIndentations: [0],
                      },
                    ],
                    absoluteBoundingBox: {
                      x: 559,
                      y: -783.5,
                      width: 70,
                      height: 27,
                    },
                    absoluteRenderBounds: {
                      x: 559,
                      y: -783.5,
                      width: 70,
                      height: 27,
                    },
                    constraints: { vertical: "TOP", horizontal: "LEFT" },
                    layoutAlign: "INHERIT",
                    layoutGrow: 0,
                    layoutSizingHorizontal: "HUG",
                    layoutSizingVertical: "HUG",
                    clipsContent: true,
                    background: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    fills: [
                      {
                        opacity: 0.5,
                        blendMode: "NORMAL",
                        type: "SOLID",
                        color: { r: 0, g: 0, b: 0, a: 1 },
                      },
                    ],
                    strokes: [],
                    cornerRadius: 20,
                    cornerSmoothing: 0,
                    strokeWeight: 1,
                    strokeAlign: "INSIDE",
                    backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
                    layoutMode: "VERTICAL",
                    itemSpacing: 4,
                    counterAxisAlignItems: "CENTER",
                    primaryAxisAlignItems: "CENTER",
                    paddingLeft: 30,
                    paddingRight: 30,
                    paddingTop: 4,
                    paddingBottom: 4,
                    layoutWrap: "NO_WRAP",
                    effects: [],
                  },
                ],
                absoluteBoundingBox: {
                  x: 254,
                  y: -783.5,
                  width: 375,
                  height: 27,
                },
                absoluteRenderBounds: {
                  x: 254,
                  y: -783.5,
                  width: 375,
                  height: 27,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "STRETCH",
                layoutGrow: 0,
                layoutSizingHorizontal: "FILL",
                layoutSizingVertical: "HUG",
                clipsContent: false,
                background: [],
                fills: [],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "INSIDE",
                backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                layoutMode: "HORIZONTAL",
                itemSpacing: 47,
                primaryAxisSizingMode: "FIXED",
                primaryAxisAlignItems: "SPACE_BETWEEN",
                layoutWrap: "NO_WRAP",
                effects: [],
              },
            ],
            absoluteBoundingBox: { x: 254, y: -856.5, width: 375, height: 100 },
            absoluteRenderBounds: {
              x: 254,
              y: -856.5,
              width: 375,
              height: 100,
            },
            constraints: { vertical: "CENTER", horizontal: "LEFT_RIGHT" },
            layoutSizingHorizontal: "FIXED",
            layoutSizingVertical: "HUG",
            clipsContent: false,
            background: [],
            fills: [],
            strokes: [],
            strokeWeight: 1,
            strokeAlign: "INSIDE",
            backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
            layoutMode: "VERTICAL",
            counterAxisSizingMode: "FIXED",
            itemSpacing: 8,
            layoutWrap: "NO_WRAP",
            effects: [],
          },
          {
            id: "10:325",
            name: "Top",
            type: "FRAME",
            scrollBehavior: "SCROLLS",
            blendMode: "PASS_THROUGH",
            children: [
              {
                id: "10:326",
                name: "TOP",
                type: "TEXT",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                absoluteBoundingBox: {
                  x: 425.5,
                  y: -954,
                  width: 33,
                  height: 19,
                },
                absoluteRenderBounds: {
                  x: 426.203125,
                  y: -950.4765625,
                  width: 31.5546875,
                  height: 11.6796875,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "INHERIT",
                layoutGrow: 0,
                layoutSizingHorizontal: "HUG",
                layoutSizingVertical: "HUG",
                fills: [
                  {
                    blendMode: "NORMAL",
                    type: "SOLID",
                    color: { r: 1, g: 1, b: 1, a: 1 },
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "OUTSIDE",
                effects: [],
                characters: "TOP",
                style: {
                  fontFamily: "SF Pro Display",
                  fontPostScriptName: "SFProDisplay-Black",
                  fontWeight: 900,
                  textAutoResize: "WIDTH_AND_HEIGHT",
                  fontSize: 16,
                  textAlignHorizontal: "CENTER",
                  textAlignVertical: "TOP",
                  letterSpacing: 0,
                  lineHeightPx: 19.09375,
                  lineHeightPercent: 100,
                  lineHeightUnit: "INTRINSIC_%",
                },
                layoutVersion: 4,
                characterStyleOverrides: [],
                styleOverrideTable: {},
                lineTypes: ["NONE"],
                lineIndentations: [0],
              },
            ],
            absoluteBoundingBox: { x: 382.5, y: -958, width: 119, height: 27 },
            absoluteRenderBounds: { x: 382.5, y: -958, width: 119, height: 27 },
            constraints: { vertical: "TOP", horizontal: "CENTER" },
            layoutSizingHorizontal: "HUG",
            layoutSizingVertical: "HUG",
            clipsContent: true,
            background: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
            ],
            fills: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
            ],
            strokes: [],
            cornerRadius: 20,
            cornerSmoothing: 0,
            strokeWeight: 1,
            strokeAlign: "INSIDE",
            backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
            layoutMode: "HORIZONTAL",
            itemSpacing: 4,
            counterAxisAlignItems: "CENTER",
            primaryAxisAlignItems: "CENTER",
            paddingLeft: 43,
            paddingRight: 43,
            paddingTop: 4,
            paddingBottom: 4,
            layoutWrap: "NO_WRAP",
            effects: [],
          },
          {
            id: "10:330",
            name: "Top Right",
            type: "FRAME",
            scrollBehavior: "SCROLLS",
            blendMode: "PASS_THROUGH",
            children: [
              {
                id: "10:331",
                name: "ABS",
                type: "TEXT",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                absoluteBoundingBox: {
                  x: 597.5,
                  y: -945.5,
                  width: 35,
                  height: 18,
                },
                absoluteRenderBounds: {
                  x: 597.234375,
                  y: -941.8828125,
                  width: 34.4921875,
                  height: 11.6796875,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "INHERIT",
                layoutGrow: 0,
                layoutSizingHorizontal: "HUG",
                layoutSizingVertical: "HUG",
                fills: [
                  {
                    blendMode: "NORMAL",
                    type: "SOLID",
                    color: { r: 1, g: 1, b: 1, a: 1 },
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "OUTSIDE",
                effects: [],
                characters: "ABS",
                style: {
                  fontFamily: "Georgia",
                  fontPostScriptName: "Georgia-Bold",
                  fontWeight: 700,
                  textAutoResize: "WIDTH_AND_HEIGHT",
                  fontSize: 16,
                  textAlignHorizontal: "CENTER",
                  textAlignVertical: "TOP",
                  letterSpacing: 0,
                  lineHeightPx: 18.1796875,
                  lineHeightPercent: 100,
                  lineHeightUnit: "INTRINSIC_%",
                },
                layoutVersion: 4,
                characterStyleOverrides: [],
                styleOverrideTable: {},
                lineTypes: ["NONE"],
                lineIndentations: [0],
              },
              {
                id: "10:334",
                name: "ABS",
                type: "TEXT",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                absoluteBoundingBox: {
                  x: 599.5,
                  y: -923.5,
                  width: 31,
                  height: 19,
                },
                absoluteRenderBounds: {
                  x: 599.8828125,
                  y: -919.96875,
                  width: 29.9296875,
                  height: 11.6640625,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                layoutAlign: "INHERIT",
                layoutGrow: 0,
                layoutSizingHorizontal: "HUG",
                layoutSizingVertical: "HUG",
                fills: [
                  {
                    blendMode: "NORMAL",
                    type: "SOLID",
                    color: { r: 1, g: 1, b: 1, a: 1 },
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "OUTSIDE",
                effects: [],
                characters: "ABS",
                style: {
                  fontFamily: "SF Pro Display",
                  fontPostScriptName: "SFProDisplay-Semibold",
                  fontWeight: 600,
                  textAutoResize: "WIDTH_AND_HEIGHT",
                  fontSize: 16,
                  textAlignHorizontal: "CENTER",
                  textAlignVertical: "TOP",
                  letterSpacing: 0,
                  lineHeightPx: 19.09375,
                  lineHeightPercent: 100,
                  lineHeightUnit: "INTRINSIC_%",
                },
                layoutVersion: 4,
                characterStyleOverrides: [],
                styleOverrideTable: {},
                lineTypes: ["NONE"],
                lineIndentations: [0],
              },
            ],
            absoluteBoundingBox: { x: 585, y: -958, width: 60, height: 66 },
            absoluteRenderBounds: { x: 585, y: -958, width: 60, height: 66 },
            constraints: { vertical: "TOP", horizontal: "RIGHT" },
            layoutSizingHorizontal: "FIXED",
            layoutSizingVertical: "FIXED",
            clipsContent: true,
            background: [
              {
                blendMode: "NORMAL",
                type: "SOLID",
                color: {
                  r: 0.09019608050584793,
                  g: 0.8627451062202454,
                  b: 0.5647059082984924,
                  a: 1,
                },
              },
            ],
            fills: [
              {
                blendMode: "NORMAL",
                type: "SOLID",
                color: {
                  r: 0.09019608050584793,
                  g: 0.8627451062202454,
                  b: 0.5647059082984924,
                  a: 1,
                },
              },
            ],
            strokes: [],
            cornerRadius: 20,
            cornerSmoothing: 0,
            strokeWeight: 1,
            strokeAlign: "INSIDE",
            backgroundColor: {
              r: 0.09019608050584793,
              g: 0.8627451062202454,
              b: 0.5647059082984924,
              a: 1,
            },
            layoutMode: "VERTICAL",
            counterAxisSizingMode: "FIXED",
            itemSpacing: 4,
            primaryAxisSizingMode: "FIXED",
            counterAxisAlignItems: "CENTER",
            primaryAxisAlignItems: "CENTER",
            paddingTop: 4,
            paddingBottom: 4,
            layoutWrap: "NO_WRAP",
            effects: [],
          },
          {
            id: "10:335",
            name: "TopLeft",
            type: "FRAME",
            scrollBehavior: "SCROLLS",
            blendMode: "PASS_THROUGH",
            children: [
              {
                id: "10:339",
                name: "ClockIcon",
                type: "FRAME",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                children: [],
                absoluteBoundingBox: { x: 256, y: -940, width: 28, height: 28 },
                absoluteRenderBounds: {
                  x: 256,
                  y: -940,
                  width: 28,
                  height: 28,
                },
                constraints: { vertical: "SCALE", horizontal: "SCALE" },
                clipsContent: true,
                background: [
                  {
                    blendMode: "NORMAL",
                    type: "IMAGE",
                    scaleMode: "FILL",
                    imageRef: "6bb4341faf39ebc5ffa09f2e8748574503cd7152",
                  },
                ],
                fills: [
                  {
                    blendMode: "NORMAL",
                    type: "IMAGE",
                    scaleMode: "FILL",
                    imageRef: "6bb4341faf39ebc5ffa09f2e8748574503cd7152",
                  },
                ],
                strokes: [],
                cornerRadius: 8,
                cornerSmoothing: 0,
                strokeWeight: 1,
                strokeAlign: "INSIDE",
                backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                effects: [],
              },
            ],
            absoluteBoundingBox: { x: 238, y: -958, width: 64, height: 64 },
            absoluteRenderBounds: { x: 238, y: -958, width: 64, height: 64 },
            constraints: { vertical: "SCALE", horizontal: "SCALE" },
            clipsContent: true,
            background: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
              {
                blendMode: "NORMAL",
                type: "GRADIENT_RADIAL",
                gradientHandlePositions: [
                  { x: 0.4999999951963331, y: 0.4999999959560998 },
                  { x: 0.5000000315179153, y: 1.0937500335582488 },
                  { x: -0.09375004240581597, y: 0.5000000322776844 },
                ],
                gradientStops: [
                  { color: { r: 0, g: 0, b: 0, a: 0 }, position: 0 },
                  {
                    color: { r: 0, g: 0, b: 0, a: 1 },
                    position: 0.8399999737739563,
                  },
                  {
                    color: { r: 0, g: 1, b: 0.6392157077789307, a: 1 },
                    position: 0.8400999903678894,
                  },
                  {
                    color: { r: 0, g: 1, b: 0.6399999856948853, a: 1 },
                    position: 1,
                  },
                ],
              },
            ],
            fills: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
              {
                blendMode: "NORMAL",
                type: "GRADIENT_RADIAL",
                gradientHandlePositions: [
                  { x: 0.4999999951963331, y: 0.4999999959560998 },
                  { x: 0.5000000315179153, y: 1.0937500335582488 },
                  { x: -0.09375004240581597, y: 0.5000000322776844 },
                ],
                gradientStops: [
                  { color: { r: 0, g: 0, b: 0, a: 0 }, position: 0 },
                  {
                    color: { r: 0, g: 0, b: 0, a: 1 },
                    position: 0.8399999737739563,
                  },
                  {
                    color: { r: 0, g: 1, b: 0.6392157077789307, a: 1 },
                    position: 0.8400999903678894,
                  },
                  {
                    color: { r: 0, g: 1, b: 0.6399999856948853, a: 1 },
                    position: 1,
                  },
                ],
              },
            ],
            strokes: [],
            cornerRadius: 20,
            cornerSmoothing: 0,
            strokeWeight: 1,
            strokeAlign: "INSIDE",
            backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
            effects: [],
          },
          {
            id: "10:327",
            name: "Bottom",
            type: "FRAME",
            scrollBehavior: "SCROLLS",
            blendMode: "PASS_THROUGH",
            children: [
              {
                id: "10:328",
                name: "BOTTOM",
                type: "TEXT",
                scrollBehavior: "SCROLLS",
                blendMode: "PASS_THROUGH",
                absoluteBoundingBox: { x: 407, y: -651, width: 70, height: 18 },
                absoluteRenderBounds: {
                  x: 408.71875,
                  y: -647.8671875,
                  width: 66.8046875,
                  height: 12.1875,
                },
                constraints: { vertical: "TOP", horizontal: "LEFT" },
                fills: [
                  {
                    blendMode: "NORMAL",
                    type: "SOLID",
                    color: { r: 1, g: 1, b: 1, a: 1 },
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: "OUTSIDE",
                effects: [],
                characters: "BOTTOM",
                style: {
                  fontFamily: "Helvetica",
                  fontPostScriptName: "Helvetica-Bold",
                  fontWeight: 700,
                  textAutoResize: "WIDTH_AND_HEIGHT",
                  fontSize: 16,
                  textAlignHorizontal: "CENTER",
                  textAlignVertical: "TOP",
                  letterSpacing: 0,
                  lineHeightPx: 18.3984375,
                  lineHeightPercent: 100,
                  lineHeightUnit: "INTRINSIC_%",
                },
                layoutVersion: 4,
                characterStyleOverrides: [],
                styleOverrideTable: {},
                lineTypes: ["NONE"],
                lineIndentations: [0],
              },
            ],
            absoluteBoundingBox: { x: 383, y: -656, width: 118, height: 29 },
            absoluteRenderBounds: { x: 383, y: -656, width: 118, height: 29 },
            constraints: { vertical: "BOTTOM", horizontal: "CENTER" },
            clipsContent: true,
            background: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
            ],
            fills: [
              {
                opacity: 0.5,
                blendMode: "NORMAL",
                type: "SOLID",
                color: { r: 0, g: 0, b: 0, a: 1 },
              },
            ],
            strokes: [],
            cornerRadius: 20,
            cornerSmoothing: 0,
            strokeWeight: 1,
            strokeAlign: "INSIDE",
            backgroundColor: { r: 0, g: 0, b: 0, a: 0.5 },
            effects: [],
          },
        ],
        absoluteBoundingBox: { x: 222, y: -974, width: 439, height: 363 },
        absoluteRenderBounds: { x: 222, y: -974, width: 439, height: 363 },
        constraints: { vertical: "TOP", horizontal: "LEFT" },
        clipsContent: true,
        background: [
          {
            blendMode: "NORMAL",
            type: "SOLID",
            color: { r: 1, g: 0, b: 0, a: 1 },
          },
        ],
        fills: [
          {
            blendMode: "NORMAL",
            type: "SOLID",
            color: { r: 1, g: 0, b: 0, a: 1 },
          },
        ],
        strokes: [],
        cornerRadius: 28,
        cornerSmoothing: 0,
        strokeWeight: 1,
        strokeAlign: "INSIDE",
        backgroundColor: { r: 1, g: 0, b: 0, a: 1 },
        effects: [],
      },
      components: {},
      componentSets: {},
      schemaVersion: 0,
      styles: {},
    },
  },
  images: {
    "93ed9799cded33b60fe0e5d950ae40fea0b0ff69":
      "https://s3-alpha-sig.figma.com/img/93ed/9799/cded33b60fe0e5d950ae40fea0b0ff69?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=bsqV7xiBUNVOFf44WP5xhxruAtDw9RCx~08Vqe11yQMm5TAF9rbA-~3872njBgLcRYm1SY0XdvJW~y5g3atGhwvo0KP38o6utcJ9bs-4PJ6Ra~9Z-ZS58VL8y0pWzJ2CzVkKfBFza8pN3jyeS~rkt15HYKYqFMiA-S2rxcvYifVXu2JWPAy3CaeEi00hN63NAwpuZfj~oiFTzuufM7w8o5RBkq9f~BTKYwEs5Byj1nASOxPiRGwQiQj3uOdBeVtys2ahKCb7Vv~2F3-cNaezZlp8YowSD6devH0qGuWVRYz6swS-4RmANdw7hNyRqO-oQM38JOxjgnwteBKYPg2uXg__",
    "6302bba90459b03a698184fd350f6c69a73e56bd":
      "https://s3-alpha-sig.figma.com/img/6302/bba9/0459b03a698184fd350f6c69a73e56bd?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=lxxU~lBP9ghtu1~wurhPklTW2P932t2WAjosJH6fc6PyG2cucEUxBl0TKPCUh3Wx4Nh3uCNSfEsJ8n2tzQLVC2RfzFeW71sdUTKfInva0iLdwY1dxi8xWHFwxgjIQtkNPgcl5zzndGKgodrVrStaCriUPjhN3KaZe~-BPj-jBrCqlIHxT3IQ~rItaWGEAgJ1xw7c-kAqap2PMizeZoUahG68nO0HqAhmfsAnZ4IJ0lDT52ycQ7Zse4y6Nm0dGtD~PuzXJvCfLiwIiW4sMY1DLd71G25kOrJyhYAONbKtL~5f1PVuhRYlPuLnWKzduERw6Z8JSGb9FV7OafPIYQ64yw__",
    "7f7998d5de377c8c93e866d15b2b3b5f084e41d6":
      "https://s3-alpha-sig.figma.com/img/7f79/98d5/de377c8c93e866d15b2b3b5f084e41d6?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=U098btA1Iqv92PSWJmaIgdEZyO~d46dfGZ1GcZYU4QBrPQleNxP4VVcFi2TllOd3rqTKOgAImOMKlOW7iz9-FwRyEo1ad8YhFDUkvnaGJQ3HLxnpPcQmke62uJClnKNAKqoINiSbDsjdCW~0yx17Vy4mvQUrZbunuZ7Ggv4WP5O6GrY9eTxYJtsiw2RC~6G~FhxhxVV2AShqYrc4dFnsdSKzCeYfuNPamzAINGT9qHZPQDn-Ybew5p8I3xrrLSkDtxvz-LCRT5X1IDz08GfyoSeJXAm3fVKPHNzoUo8OYntnZabeh3dLa-FdDGkNePhK4G~VE-jN1ZTsnSAn4uH5qg__",
    a3ead53e3dfab416c49db546bb9f93f6482f5af4:
      "https://s3-alpha-sig.figma.com/img/a3ea/d53e/3dfab416c49db546bb9f93f6482f5af4?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=XctJB4x~DbeoQo92b4etc4-G~qUDmilCyKutIGqQ70PcFrQYWznP0CIMckUgx8mTG9lZ5Lyno95h2gjU5z5BrZBI1ussRpjTDV2~-Vzc1JXVkUbNFY4K6N3JU0yyYcd8RJZu3ccCHC4S66qk5kmOWoPJ0Ba7QxzO~XhVeB2FBGFulSLVbvAGY1oxuqSLmEh70MlBvWqWvOIixsnV0TM~E1chxXSLs0FaIaJJ34f03sc8W2Qr-Ub0mthSOvXZ0CRVP7MhVW1LIFI-6v2xjrokReC23JVxTIhBbFSadXZpzpJeiXje~w5d4mYOqmcwWkpC6x5Xb~mjAc2E87aWeENdIQ__",
    "99b2744a7ca1c1a028c042222652151fd9f18105":
      "https://s3-alpha-sig.figma.com/img/99b2/744a/7ca1c1a028c042222652151fd9f18105?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=XjEYOZBpY4uWmBDq8KpCK5g5WxUCmWTyLJuRJHhMJFrfy~tXG2dq-5NQxUFu8sd03UuM0R4nshXHBTmxOHCMsv83FC7PrVKXhg46iow6HUoxCt-f6TD0NLyyD25WZa3AezosIozYk6v0lFrssr85URVbHNrAajnrihJWYaQy2dWut6A8ULGCgt1t5eQoZ8r~cYich2UnMwDzK4LBp5M7C5oo6D2iLetgviUmQpVW2rCk6PUOaBKp9Y5n-aJmzpf~6HQPYZeaqdpoP-PbGKRfeABm2dK4h9712g8LHbj-pkZmj93ENHJBsk7fYTQMFEeieVaBuEEk4TS2axZMVCeE5g__",
    "23d3e9e4ad683e93b6921f3b05f711991f3829ea":
      "https://s3-alpha-sig.figma.com/img/23d3/e9e4/ad683e93b6921f3b05f711991f3829ea?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=nn5SIcqwxU1YBGIg6NaO~C3OMlxIFOgu48d3Ffi7MkvmzagT1giV6NcOBt-jrwWZvitCUXhKdEYK7Z9JStRiaNiM115qhqO8cB9cf9CK5qdlFASVpPlRZW8T155B0r4ZBYk8bL~rgIMWCl8sp4sE-WXsbkVDuFHbc3EZwX6QYF3W~AT7-IzApJLSxgLLppUZ9WvaPZrukIkRifEn7pzppcwO8bLQfQxFOpe2ZzTK1891X728yPdLGIchK5OvqDriUN0MRBbJ11m9QBP1jsxowTsQzwsHZ1F8gx-m3tADjZwVUvcHIOEbRn42JjHZXbmUCsNXOderYnH8ywzDCjsAmQ__",
    "27a94a90bc2c0aa7400df9f2f4d4edb462405e9d":
      "https://s3-alpha-sig.figma.com/img/27a9/4a90/bc2c0aa7400df9f2f4d4edb462405e9d?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Q-NUqrMqUW0gf~RqhT42uYt6M8xAdI6ta56t-ksnn-TKjzPJrTkQAbZUJDdTqUn7RDRuvS28-TbpPHqpdnD3GUo~akuqsTYBqxohovlVMyQ0PWHJX3qTpCOFT6hmqfQpqkt8wKFEWGL9PxPGx98fvOnMW3B2AwNeBaJN-jDTf0NhZva7dlP0pl2U0IofnivRTqyASVpcG8s1msK8ARjQBfCKgIPsQ6dHw7teRHedTow4fU8o0kdls1TWkkawwB3LO1ng5dQAPmeX-TxOyklz75PeBfmpEMzy9Ahx4Nuro0CyqAp6TxbZT9yFQoKJtsnNQBJZEIQOIzUZhB5OFXCaOQ__",
    "21a1dbdf883f16f401745db4882aed6e40b2a0fa":
      "https://s3-alpha-sig.figma.com/img/21a1/dbdf/883f16f401745db4882aed6e40b2a0fa?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=n44c~nsq2o3pQ4cenrgVZqm1BlTH~lwxGidbNn1LRSjRISgi~UAycm9zq5-l69eXpB~L1sZPWGFmz9yu4oXeowqFddgeOf8CTlV5wHaE2vbkmswrT2hlA8uuLYsTy55YIB2GwiBIaQjTJU6CgPn5B579EAYSPvJ0El6sfBzjOnlkxPTZxhQ4BzgFwQzscvMfmHQ8zV4TjZg0aw7jnqtwrgnv~zdwIihJfBaGgDW7uQTl6PyWXoBQ0coxXKjBnrmRoZ1rcIHxV1pa3yXAMzpPLtueQYQtzLS~CNnioqMAgYDD8c-XqwNFQI7Knk1X9nKX93IZXvrPEcEKIeenl1~kgw__",
    "14629c122014931d485f150d06ee9126673ae768":
      "https://s3-alpha-sig.figma.com/img/1462/9c12/2014931d485f150d06ee9126673ae768?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=gbUuQvvaYtuffjhFh1KFnQATw3xIqfQutm~ou4EH5mIAjwV9uWCUaxd3UvbrukZ1vaCkRZxfRpu0aNXa5ZlE0FF2InAs~DAHpV-rGviODQevw6~LouIfOLhKXbWAjZqPHfb-Xwr5vC9aA-SilqEPP-yaEFLlMxjz5LxWq8Vg9z72VgguDpHzkNndzRh4VOJ4lvM4jk-PhTvU94LcGOd2V3kjPtuOLC20Tqe2DnijfxchJrOfVKdR0wglaUoruyTIkoaA51cyVM0hruhKo~tNAxrOGznhvwgYsDtLTk-gimZms-S~8wQF52FUKu3gcMg8eQsuNfuasGtOmvQp6kd-uw__",
    f0109d4d38bf13104c58a1e7ae405be05b77bad7:
      "https://s3-alpha-sig.figma.com/img/f010/9d4d/38bf13104c58a1e7ae405be05b77bad7?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=C~qcd-gOZl0IlFRdtsy2G3Ve8PyCivfIKCkkJYZkm-1YegoNlPwCc2wN7cF1xS6nuGYgvDKTBHCo1hzRLDGMQlzTKO2roptJxpIL2EI0V3YQcxAPU474EJ7BqR5-p6eu3~SCpiiOD4FXH7JFNAvAN2yEVlZUUPE41pPZO89l9vA~Y988hNmKEkaCjxPorb61AR8yk8u6yx7TXsuUsIXhlbxFVSJ09~hE48~TVBqJPN3PvnqO4g8cGkeiz68oTJyAYjh2tyoyUUBEu34sjCbVDcIIIUIy3f3j8h-f5ro-qChyH7mJHV86EKN9nqLIjSMZoDCwaNDgMiYxNzH1y3Cbsg__",
    "60af3bc0602264ed5a0e785f8efafdaea0552efd":
      "https://s3-alpha-sig.figma.com/img/60af/3bc0/602264ed5a0e785f8efafdaea0552efd?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=aNFqJd~WdPy-PfxnTiKkANSmK5X90cxuwr5n5d78EVdTAbRma1TePrmm4VHWBtyXBreiMbhIxCwI5BVfvic4rNMuTjT~hjzu4T5a5tdCz9jR0jlshk61c86Hapy4nSa4KrorfrHqA9uWDE1lDUWl4O9Yqz73Gna86EtsWx-skBSbuQtc7Zfk0Tqr0b2EOrDvxPGX~AFFoX2oeioxGvG7Jnos5OavT6GeYzZQw-4IKfXomVatN6GEf4knAb~amILm0VpQbBxt9B~K0QSlm7kJkjKtcgxFMY-ClJvMMGmz0JZCE2UKqMgw6~9~zNcKsfq3XfwreB7gwCH4~lQIbqeiGg__",
    c80b974e0ffa02bb23e285794d24420ac0535134:
      "https://s3-alpha-sig.figma.com/img/c80b/974e/0ffa02bb23e285794d24420ac0535134?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=nmlhSuPkJz8bDNIAysW1fYHUV6pY4vy51uqzJOLrlGzKBl3Fd6-yLZswd4mOlyC~jwjVkrqt8z90R-aqFC16HLJLbKF84Eb5vT78zvq7vaAcy0D8bYoU4k8O2AwNty8v58vIeG~3wtWUCZSAfkYeIFHe~KSUNhTK4wirMZRakZM8XoKu4GoTLeLteL9GK709cw0WVeUit6xyV94PVosoHoAsmnSdExAWIQgQrrtxHVIfVaAJR7fxkHr7oiAZWp1BZy52eZ7yf~y5lPAHjpqV~0FN-ILnk98lv33Eehbdo4IB4N7xTuup0QLwFmpGhNUpZkjPbyHlQBFJ8C5jOjHL~Q__",
    "6bb4341faf39ebc5ffa09f2e8748574503cd7152":
      "https://s3-alpha-sig.figma.com/img/6bb4/341f/af39ebc5ffa09f2e8748574503cd7152?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=KqgnDxXTSBo0g3KPnQU-4r-smZ4xhtn6vZ4jnt2559yLRAp7y3Sx3EB0gC63utO69l9LBS1JQ-xVKEcQeipnpQnFH~OIMXeRX5JsFTX98BARq4yU9~MN6iYve0XRkp8JpDsfO0rN34NQY7vh9CT9b7Gptsf1C5Ey5KQO4Wf7mPyIZa8JvMl9MRO9AP0AtU4jX~obTmuX0C~-0ZIYJDmemwSkgBUHPLP8crUkFaI7u3tJscHFbj3-x3c3ZFqfvCdRlCwS3kQSS2Hes-V9y7Dap4cEn-5sqG5r6eTMJlx4H54tQidSmRZMa0Q42rqiQymHN9UabZheah~jrYMivdkBbQ__",
    "3dbc4fb967e864e47aead9dd3d8c9a35257a08e3":
      "https://s3-alpha-sig.figma.com/img/3dbc/4fb9/67e864e47aead9dd3d8c9a35257a08e3?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=crAzIFosp4Vs7yYlowz9LPpBpkJmzeJhBSzsHcjb6vgaHGv5je5gBJPCL8NE8FuRyVhpiaXpv-b-oCgeon3W~6cwnyNY5OYr0nO7~96ZMYFCdnOdCOpqtluj1DX9IZc0Ui3ryOlTRaDnaIQ~gfDmmq8jgQRBozBrs65gql~47opV5OnB36fSsgUs-z6f8f8J~mvtEmXwF~7-Uv9d9L4OXjC7~HB5HNPOdVD4bhTOKVmR24JMKd~jJxlH4kVabYXHQFvG-03ZgVvk-Pvv1AufGzRSXLMjEH1x9bzv5NMH5afc1MAOLob5TiMPnvGb6qKWMVse7RP46eiwYLzuzpby6w__",
    f22aecc49d2cfbab5c6652f8f01f24d78e4b7ddb:
      "https://s3-alpha-sig.figma.com/img/f22a/ecc4/9d2cfbab5c6652f8f01f24d78e4b7ddb?Expires=1711324800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=atiWrgsLjurqZW9GS-ohtmLFWJ7u3WfgwLoet7-qCg1OA6sWi9XBQ5NDgoWufAdOCt9cSLCVnzpJQIXDEF~ioCfmYSo2MQRckUHYu-uXZ8NENb0eMwnb-Oq-ozfm4pa~xnMClcDc4pSVBRYowRU2RbSG9zGJtDByoC7rOH8h1kMzVmuA-YD2jyfaqlTTVx1XVkw1xzG5FwcbgIPc6TLZU~JDN~~0UX5poI2LYnFyzpyj9J4avsUk5p~HAvUwugCylu8HtnzYGTH6pDoMkbmVswe27fb5tfsXbMSvesxokKuBAvDaXVt6WfM8bCTpaQj0FkyiMfovRjB0OmbUyuHR2A__",
  },
};
